### ISSUE TITLE
[Discovery] Build Cataloguer tool to check record display

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#10]
Standalone tool
Cataloguer enters catkey
Blacklight view pulls data from Symphony WS and builds a record display on the fly.

**Comment by redlibrarian** [comment]
OK, after discussing this in ITS, it looks like the following might be possible:

- [ ] Add cataloguer_tool controller to NEOS Blacklight
- [ ] Add view which allows cataloguer to enter a catkey
- [ ] Controller uses Sirsi WebServices to pull down the record (oh right, this is where it gets tricky - you can't get a marc record from SirsiWS, which is what SolrMarc/Traject will be expecting).
- [ ] Once the marc record is downloaded, simply run rake ingest to index the record.
- [ ] Present the cataloguer with a link to the record view.
- [ ] In terms of infrastructure, this will require deploying NEOS Discovery and standalone solr to its own server.

**Comment by redlibrarian** [comment]
The obstacle to this approach is not being able to get a MARC record from Symphony. As much as I hate to do it, the only choice may be to get the record using z39.50, so I'll have to dig into that and see how feasible that it.

**Comment by redlibrarian** [comment]
@redlibrarian to get this implemented ASAP. We can launch the beta version now, with messaging to staff that this will be available soon enough that they can kick the tires and get used to it well before the public launch.

**Comment by redlibrarian** [comment]
OK, I've made a start on this. Right now going to /cataloguing will present the user with a form to enter a catkey. That record will be saved as tmp/records/<catkey>mrc. The next step is to ingest it. What we'll need to do is run a local solr and create a rake task that will ingest the contents of tmp/records into the local Solr. (Next steps). While this wouldn't *absolutely* need to run on its own server, I would be worried about accidentally confusing the Solr URLs if we run it on the same server as the real application. The cataloguing tool server should be firewalled from the production solr-cloud.

**Comment by redlibrarian** [comment]
This is completed in UAL discovery. We're just working on deploying it there and then we can see how it works.

**Comment by seanluyk** [comment]
@weiweishi will talk to Kenton about the need for a separate environment for this tool

**Comment by seanluyk** [comment]
@weiweishi what's the status on the environment tool?

**Comment by seanluyk** [comment]
Closing this issue as it duplicates the more fleshed out one #205
