### ISSUE TITLE
Institution specific URL being displayed for all institutions

### ISSUE THREAD

**Issue by Andeebee** [ualbertalib/NEOSDiscovery#104]
A single institution's access URL for an e-resource is being displayed for all available institutions.

For example:
https://catalogue.neoslibraries.ca/catalog/8054410

The RDC specific URL with proquest ebooks is being displayed for all institutions. 

Not currently happening in UABlacklight:
https://library.ualberta.ca/catalog/8054410

Primarily an immediate issue for URLs that have an institutional identifier. Examples found for Proquest ebook central/ebrary, Films on Demand, Credo reference, Kanopy streaming.

**Comment by redlibrarian** [comment]
OK, I think I've fixed this (and the related problem noted in #85 ). I've tagged a new code release and when it's deployed we can verify.
