### ISSUE TITLE
Database growth

### ISSUE THREAD

**Issue by nmacgreg** [ualbertalib/NEOSDiscovery#105]
Like our other Blacklight-based applications, this has a database table named 'sessions' (for instance), which seems determined to grow without bound.  Please compose a rake-task (or whatever is appropriate) that I can call from a (weekly? daily?) cronjob, to limit the number of rows retained by any appropriate database table.  
At least 'users', too, but think about all tables: 

* ar_internal_metadata
 * bookmarks
 * schema_migrations 
 * searches
 * users

**Comment by redlibrarian** [comment]
@nmacgreg I ported the rake task you created for Discovery over to this project. Once the next release has been pushed to production, you should be able to test **rake sessions:cleanup**
