### ISSUE TITLE
Add link to My Account

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#109]
@nnunn We forgot to include this, though it exists in iLink. The link should be to https://myaccount.library.ualberta.ca/barcode

**Comment by nnunn** [comment]
So I just need to add a 'login' link to the header?

**Comment by redlibrarian** [comment]
Yes, I think that's it.
Thanks.

**Comment by nnunn** [comment]
Ok that's up in master. Want me to cut a release or do you have other stuff to do?

**Comment by nnunn** [comment]
K done.
