### ISSUE TITLE
"forgot pin?" goes to U of A page

### ISSUE THREAD

**Issue by douellette** [ualbertalib/NEOSDiscovery#115]
I also would've tried putting a hold, but again wasn't sure if that was working. Also, the "What's my PIN" link goes to the UofA's page - you'll probably get a few comments about that, but I'm thinking that's more of a placeholder at this stage.

from beta-test feedback

**Comment by redlibrarian** [comment]
I've asked the web developer responsible for those pages about this.

**Comment by redlibrarian** [comment]
This now points to the generic NEOS page.

**Comment by Andeebee** [comment]
Forgot PIN still points to iLink site - change to WS version. 
Branding a mix between old NEOS/new NEOS/UA - update to a consistent look and feel (new NEOS).

**Comment by seanluyk** [comment]
@Andeebee I'll check on this with Natasha/Jeremy.

**Comment by seanluyk** [comment]
@Andeebee - just waiting for a test environment so Jeremy can mock this up, shouldn't be long

**Comment by seanluyk** [comment]
Forgot pin is going to a generic web services NEOS page, not the iLink interface, so this issue can be closed: https://myaccount.library.ualberta.ca/barcode/passwordresetstep1
