### ISSUE TITLE
"Institution limiter" Should it be alphabetical?

### ISSUE THREAD

**Issue by douellette** [ualbertalib/NEOSDiscovery#116]
There were multiple comments from the beta-test feedback about having difficulty finding one's one institution in the list when filtering by institution.  2 respondents commented that it would be easier if institutions were listed alphabetically.  

"Would like to see Institutions listed in alphabetical order in the "Limit your search" area- I had difficulty quickly picking out my own institution."

"When choosing a library or institution, on either the "Limit" section or under "More Options" is there a reason they aren't listed alphabetically? They are listed numerically, I believe. It takes longer to find the institution you are looking for. typically, in my experience, when people are limiting by location, it is because they have a specific location in mind and want to find it, not because they are looking for the location with the most titles. Would there be a different reason why they would be listed numerically that I am missing?"

Kristine Plastow would like a response

**Comment by redlibrarian** [comment]
I've made this change. Because the labels are mapped and are not part of the indexed data, this *may* not work perfectly in every case, but it's as close as we can get.
