### ISSUE TITLE
search button on advanced search/more options

### ISSUE THREAD

**Issue by douellette** [ualbertalib/NEOSDiscovery#119]
"Put another search button on the top of the page when in the "More search options" - there is way too much scrolling to get to the bottom of the page and find the only search button there, especially after selecting additional attributes."

Katalin Ormay would like a response.

**Comment by redlibrarian** [comment]
@nnunn I think we did this with the UAL advanced search (adding a search button to the top). That current search button is broken right now (see #127) - if you have a chance can you look at both of these?
