### ISSUE TITLE
What is my Pin page needs to be NEOS branded page

### ISSUE THREAD

**Issue by kzarft** [ualbertalib/NEOSDiscovery#122]
Feedback from Director's meeting. When you click on the Place Hold button, it takes you to the NEOS branded "Barcode Login Form", but the "Forgot Pin?" link on that page leads to the UofA branded "What's my Pin page" https://web.library.ualberta.ca/myaccount/pin/.  We need a new NEOS branded page for the "What's My Pin?" page. Same issue as #115

**Comment by kzarft** [comment]
This is the same as issue #115

**Comment by redlibrarian** [comment]
I've asked our web developer responsible for those pages about this.

**Comment by redlibrarian** [comment]
These now go to NEOS versions of the relevant pages.
