### ISSUE TITLE
Unfriendly login error

### ISSUE THREAD

**Issue by paulpype-goa** [ualbertalib/NEOSDiscovery#123]
When you attempt to log in to place a hold, and your login fails (due to invalid barcode or PIN), you get a plain white page with the message "Security Exception query failed: Unable to log in."

Can we make this a little more user-friendly?

**Comment by redlibrarian** [comment]
I've asked our web developer responsible for that page to look into it.

**Comment by redlibrarian** [comment]
It now flashes up "invalid username or PIN" on the same screen as the login.
