### ISSUE TITLE
Serials Summary Holdings statement(s)

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#130]

**Comment by redlibrarian** [comment]
This is always complicated to do. @Andeebee what did we decide on Friday?

**Comment by redlibrarian** [comment]
Would this be sufficient? @kzarft @Andeebee 

![screenshot from 2018-07-23 12-57-44](https://user-images.githubusercontent.com/1093066/43097033-0fbf296c-8e78-11e8-9f1e-1c7ace9105f4.png)

**Comment by kzarft** [comment]
It looks fine to me, but we don't have a lot of journal records @redlibrarian. Would the summary record also show on a serial record like this https://catalogue.neoslibraries.ca/catalog/962123?

**Comment by redlibrarian** [comment]
@kzarft It doesn't look like it. When I look in iLink, there's no summary holding's statement for that record, so I think it doesn't apply to something like this.

**Comment by redlibrarian** [comment]
Otherwise this looks good in test.

**Comment by redlibrarian** [comment]
Closing to keep todo's clear.
