### ISSUE TITLE
NEOS Free 856 URL doesn't seem to work

### ISSUE THREAD

**Issue by douellette** [ualbertalib/NEOSDiscovery#133]
Sorry if I'm not totally understanding this comment from the feedback form.  It sounds like the URL in the 856 field isn't showing up for "neos free" items.  See the whole comment: 

"Record https://catalogue.neoslibraries.ca/catalog/8191420 does not include a link to the resource, while as an example, https://catalogue.neoslibraries.ca/catalog/8189025 does. The bibliographic record for 8191420 contains link information:
856  40|3Free Access|uhttp://www.jstor.org/stable/10.20851/j.ctt1sq5w52|zfrom JSTOR
Record 8189025 has:
856  40|3University of Alberta Access|uhttps://doi.org/10.1017/CBO9781139173735|zfrom Cambridge Books Online
Is it the |3 information that is making the difference? |3Free Access is the text used for freely available eresources that all NEOS members can access, about 150,000 records.
Please contact me if you need to follow-up! Thanks, Amanda N. in Bib Services"

**Comment by redlibrarian** [comment]
@douellette I'm pretty sure I fixed this in development - we can verify when the release is in production.

**Comment by redlibrarian** [comment]
Hmm. This still isn't working. Investigating...

**Comment by redlibrarian** [comment]
Fixed in dev. We'll see when it gets push to production.
