### ISSUE TITLE
URLs not appearing for Alberta innovates or kings. 

### ISSUE THREAD

**Issue by douellette** [ualbertalib/NEOSDiscovery#134]
The links to ebooks don't always appear fro Alberta Innovates.  I.e. https://catalogue.neoslibraries.ca/catalog/8095099

Sorry if this is redundant.  Will the solution to #129 and #114 fix this for Alberta Innovates as well?

**Comment by redlibrarian** [comment]
@douellette this is the same as #133 , I think. I've fixed it in dev, we can take a look when the release is in production.

**Comment by redlibrarian** [comment]
This appears to be working now.
