### ISSUE TITLE
change Northern Lakes website and pick up location

### ISSUE THREAD

**Issue by douellette** [ualbertalib/NEOSDiscovery#137]
Copied and pasted from the form so i don't miss anything: 

"The link to the NLC Library website should be http://northernlakescollege.libguides.com

The hold pickup library includes both Slave Lake and Grouard libraries. The current catalogue has Northern Lakes College with no campus stipulated, which is what we want, all routing to Slave Lake.

The links on our Neos Library information page have not yet been corrected and the email addresses have not yet been replaced with the inquiry form link. (This went to libhelp in early March.)"

**Comment by redlibrarian** [comment]
I saw the ticket this morning - it was in the wrong queue. I've assigned it to the right queue; it should be updated early next week.

**Comment by redlibrarian** [comment]
I've updated the NLC homepage link in Blacklight. The NEOS website issue isn't part of the Blacklight work, but should be fixed soon.
