### ISSUE TITLE
double internet access links for lakeland

### ISSUE THREAD

**Issue by douellette** [ualbertalib/NEOSDiscovery#138]
There seems to be some odd anomalies of lakeland having double internet links sometimes.  i.e. 

https://catalogue.neoslibraries.ca/catalog/6740041
https://catalogue.neoslibraries.ca/catalog/6740050
https://catalogue.neoslibraries.ca/catalog/6740049

**Comment by douellette** [comment]
There are a few that do this for U of A too i.e. https://catalogue.neoslibraries.ca/catalog/7401549

**Comment by redlibrarian** [comment]
Interesting. If you check the Symphony record, Lakeland *does* have two multiple internet copies: 
http://www.library.ualberta.ca/permalink/opac/6740041/WUAARCHIVE
http://www.library.ualberta.ca/permalink/opac/6740050/WUAARCHIVE

If this is a problem (maybe it isn't) then it's something for bib services to fix).
Looks like it's true for the UAL copies as well: http://www.library.ualberta.ca/permalink/opac/7401549/WUAARCHIVE

**Comment by redlibrarian** [comment]
@kzarft Do you know if this is correct cataloguing practice or not? For discussion on Friday.

**Comment by redlibrarian** [comment]
I've add in the note in the metadata that says what platform each link is for. This should make it clear why there are multiple links showing up. Now that the data is being displayed, @nnunn can make changes to the display if we want to do something different with that information. Does that look OK for now?

**Comment by redlibrarian** [comment]
There's still an issue with the second link not displaying when multiple platforms are present. Still working on that problem.

**Comment by redlibrarian** [comment]
OK. I think I finally have this working. It's ugly but it seems to work.

**Comment by redlibrarian** [comment]
Closing to keep todos clear. We'll check all electronic links on the next deployment.
