### ISSUE TITLE
King's name change still an issue

### ISSUE THREAD

**Issue by douellette** [ualbertalib/NEOSDiscovery#139]
I have received several online forms and other communications from Shannon at Kings reminding me that the description on their catalogue landing page (https://catalogue.neoslibraries.ca/?lib=kings) still refers to them as "King's University College Library." Can you please change this to "The King's University" (not College).

**Comment by redlibrarian** [comment]
All the locations are changed - I think it's just the landing page text that needs to be fixed.

**Comment by redlibrarian** [comment]
OK, the new release is up. This looks fixed to me. @douellette Can you close the issue after verifying that it looks OK?

**Comment by douellette** [comment]
looks good to me.
