### ISSUE TITLE
245 subfield p in the title display

### ISSUE THREAD

**Issue by kzarft** [ualbertalib/NEOSDiscovery#140]
Could we add the subfield p (245) to the title display in the results list and the detail record? We have the subfield b showing but it would be helpful to show the subfield p as well.  Example of records this affects:
https://catalogue.neoslibraries.ca/catalog/6208988
https://catalogue.neoslibraries.ca/catalog/6208991

**Comment by redlibrarian** [comment]
@kzarft I looked into this, and we are currently indexing the 245p as "section name". It appears in both these records as **section name**. Just to confirm, for 6208988, should the title appear as **Health Assessment: Height and Weight**? Is this true for *all* 245 $p?

**Comment by kzarft** [comment]
@redlibrarian In WorldCat and in iLink the title appears as: Health Assessment. Height and weight
That looks correct according to the Marc 21 format information at the Library of Congress http://www.loc.gov/marc/bibliographic/bd245.html
"In records formulated according to ISBD principles, subfield $p data follows a period (.) when it is preceded by subfield $a, $b or another subfield $p. Subfield $p follows a comma (,) when it follows subfield $n.

**Comment by redlibrarian** [comment]
OK, sounds good.

**Comment by redlibrarian** [comment]
This looks good in test.

**Comment by redlibrarian** [comment]
Closing to keep todo's clear.
