### ISSUE TITLE
Edition statement missing on detail record page

### ISSUE THREAD

**Issue by kzarft** [ualbertalib/NEOSDiscovery#141]
On the results page the edition statement (250 field) is part of the title, but when you click through to the detail records page, there is no edition statement.  This forces you to flip back and forth between the results page and the detail records page to confirm the edition, if you are using the next and previous buttons to move through the list.  Could you add the edition statement somewhere on the detail records page?  For an example of this do a search for Canadian fundamentals of nursing.

**Comment by redlibrarian** [comment]
@kzarft I added edition when I added section; it should appear in the next deployment (which should be today or tomorrow).

**Comment by redlibrarian** [comment]
Because of punctuation issues and other weird cataloguing pieces, for some books the title statement now appears a bit strange; but at least all the information is there.

**Comment by kzarft** [comment]
Okay thanks! I will check once it is updated. Maybe that is why it is not appearing in the RIS format?

**Comment by redlibrarian** [comment]
I think the default fields RIS is using aren't named the same as ours - I'll look into that.

**Comment by redlibrarian** [comment]
This looks good in test.

**Comment by redlibrarian** [comment]
Closing to keep todo's clear.
