### ISSUE TITLE
Status: Internet - No links appear

### ISSUE THREAD

**Issue by Andeebee** [ualbertalib/NEOSDiscovery#142]
Example:
https://catalogue.neoslibraries.ca/catalog/7468645
https://catalogue.neoslibraries.ca/catalog/7468854

**Comment by redlibrarian** [comment]
I think this is related to #138 - I'm still trying to get those issues all sorted out.

**Comment by redlibrarian** [comment]
OK. I think I've figured this out. Sort of. It's ugly but it seems to mostly work.

**Comment by redlibrarian** [comment]
Closing to keep todos clear. We'll check all electronic links on the next deployment.
