### ISSUE TITLE
 Map AHS internet display name to include Covenant Health

### ISSUE THREAD

**Issue by Andeebee** [ualbertalib/NEOSDiscovery#143]
https://catalogue.neoslibraries.ca/catalog/7018416
http://www.library.ualberta.ca/permalink/opac/7018416/WEBSERVER

Should read as it does in iLink (Alberta Health Services/Covenant Health)

**Comment by redlibrarian** [comment]
OK, I think this is taken care of. It will be in the next release (probably tomorrow).

**Comment by redlibrarian** [comment]
This looks good in test.

**Comment by redlibrarian** [comment]
Closing to keep to-do clear.
