### ISSUE TITLE
People want to be able to print MARC from "librarian view"

### ISSUE THREAD

**Issue by douellette** [ualbertalib/NEOSDiscovery#146]
I know this has come up before but I just received feedback from someone who tried to print MARC from "librarian view" and it doesn't work.  What happens is it prints both the MARC from the pop-up window overtop of the actual record behind it. See the attached file. 

Can this be fixed? Do we need to discuss it further? 

[Librarian_view_print.pdf](https://github.com/ualbertalib/NEOSDiscovery/files/2332956/Librarian_view_print.pdf)

**Comment by nnunn** [comment]
Strange! Yes - I can fix that. I'm not sure when we are planning another deployment though so it might not be in production for a bit.

**Comment by seanluyk** [comment]
The issue of printing records from Blacklight, in general, is a big one that I think we should work towards fixing for both UAL and NEOS Blacklight. I'll get this one prioritized for UAL BL, which we could then hopefully apply to NEOS BL.

**Comment by nnunn** [comment]
Printing records is working in UAL BL except from Chrome which is a bug in Chrome and not something I can fix... Is there something else not working in printing records in UAL BL?

**Comment by seanluyk** [comment]
Yeah, Chrome is what I meant. Just tried doing this in Searchworks and don't have an issue printing from Chrome so I'm wondering if there's a fix we could borrow from them? https://searchworks.stanford.edu/view/7619587

**Comment by nnunn** [comment]
This was actually a slightly different issue, but it is fixed in development now.
