### ISSUE TITLE
Copy a record URL from NEOS Discovery to browser resulting in Error. 

### ISSUE THREAD

**Issue by Andeebee** [ualbertalib/NEOSDiscovery#150]
When you copy a record URL (e.g. https://catalogue.neoslibraries.ca/catalog/5094481) and try to paste it into another browser it will give the message: “We’re sorry, but something went wrong. If you are the application owner check the logs for more information”  
If you copy it into a the address bar in a new tab on a browser in which the Neos catalogue is already open, it works fine.  Tried in Chrome, firefox and IE11, all with the same results.

**Comment by seanluyk** [comment]
I can confirm that this doesn't happen in UA Blacklight, so I wonder if a difference in infrastructure is possibly why this is occurring? Flagging @nmacgreg for comment

**Comment by nnunn** [comment]
Ok - I've fixed this. However, when you copy a record into a new browser window it will default to the neos branding. There isn't an easy way around this. Is this ok?

**Comment by nnunn** [comment]
The fix is not yet in production

**Comment by Andeebee** [comment]
Kathy mentioned this in regards to setting up her EDS. I am not conversant in EDS - will it mean that links in the discovery tool will link to a NEOS branded version of the record?

**Comment by nnunn** [comment]
This doesn't have anything to do with EDS as far as I know...

The behaviour I am referencing is this:
If you find a record in neos blacklight and you take the url of that record and put it in a new browser window (or you email it to someone and they put it into a new browser window), you will now get that record but it will have the generic neos branding.

**Comment by Andeebee** [comment]
The other thought is that libraries routinely embedded item records in their Subject Guides. This drives quite a bit of usage that would be without library branding/support links.

**Comment by weiweishi** [comment]
@Andeebee I wonder if you see additional work required on this particular issue with this behavior? If there are other persistent link related issues, would you mind opening a new ticket and summarize the requirements? and we can discuss those with @seanluyk at our regular meeting?

I will modify the title of this issue to reflect what this one is really about (persistent record URL can mean lots of things)

**Comment by weiweishi** [comment]
Sorry I didn't realize this is a NEOSDiscovery Issue. @seanluyk would you mind following up with @Andeebee to see additional work is needed, or additional issues need to be opened? Thanks! And sorry for jump the gun!

**Comment by seanluyk** [comment]
@Andeebee this has been fixed partly. No more “We’re sorry, but something went wrong. If you are the application owner check the logs for more information” message, but when you open links in new tabs the branding defaults to NEOS.  Could you let me know if this is satisfactory for the purposes of the beta release? If so, please close the issue

**Comment by Andeebee** [comment]
Yes, I agree that it is okay for Beta release.

**Comment by seanluyk** [comment]
Closing issue as this fix satisfies requirement for beta release.
