### ISSUE TITLE
[NEOSDiscovery] Send Correction Link - "We're sorry but something went wrong."

### ISSUE THREAD

**Issue by Andeebee** [ualbertalib/NEOSDiscovery#154]
I get the error message "We're sorry" when I try to use the send correction link on a record.

Example record: https://catalogue.neoslibraries.ca/catalog/7041306
*Also, I don't know why this record doesn't have a hold button.

EDIT: Found out why it doesn't have a hold button - iLink says No Loan, Read on Site

**Comment by seanluyk** [comment]
@nnunn @nmacgreg @weiweishi @pgwillia  - flagging this issue for your attention and wondering if this is related to the SMS/email issues or perhaps something else

**Comment by weiweishi** [comment]
I will add a ticket to the backlog here to add rollbar to the NEOS Blacklight as well. Being able to see the log will help with troubleshooting issues like this.

**Comment by nnunn** [comment]
oop sorry - I guess accepting you pr closed this issue.

**Comment by pgwillia** [comment]
My fault.  I jumped the gun on calling this closed too.
