### ISSUE TITLE
Setting up Rollbar error monitoring in NEOS Discovery

### ISSUE THREAD

**Issue by weiweishi** [ualbertalib/NEOSDiscovery#155]
Setup Rollbar to monitor the NEOS Discovery to understand the error messages and help with troubleshooting with access to production logs.

**Comment by pgwillia** [comment]
Need to set or replace rollbar_token: <%= ENV['ROLLBAR_TOKEN'] %> in secrets.yml with post_server_item at https://rollbar.com/ualbertalib/NEOSDiscovery/settings/access_tokens/
