### ISSUE TITLE
[NEOSDiscovery] Add caution text to cite function 

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/NEOSDiscovery#186]
On cite this item popups, add some caution text to remind users to verify citations against current style guides:

"**Please verify the citations below with the appropriate style guide.**"

**Comment by seanluyk** [comment]
To add some more context - some of the beta feedback has indicated concern over the accuracy of citations presented here. The path of least resistance is a warning, I think. Later, we can figure out why they aren't coming through correctly.

**Comment by weiweishi** [comment]
@seanluyk there is already caution text on the pop up window:
"Please note that University of Alberta Libraries cannot ensure the accuracy of these citations. Please verify the citation in the appropriate style guide. "
Do you want additional warning/highlight the text?

**Comment by seanluyk** [comment]
@weiweishi  - not in NEOS Discovery, that's from UAL Discovery

**Comment by weiweishi** [comment]
@weiweishi will add a screenshot

**Comment by seanluyk** [comment]
@weiweishi what's the status on this?

**Comment by weiweishi** [comment]
@pgwillia would you be able to spend 20 mins on this one today so that we could have it in for a release next week?

**Comment by pgwillia** [comment]
I started looking at this one yesterday.  It's going to take a bit longer than 20 minutes because Blacklight.

**Comment by seanluyk** [comment]
Fixed in test, closing
