### ISSUE TITLE
Deployment v.1.0.47

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/NEOSDiscovery#192]
Release include changes:
https://github.com/ualbertalib/NEOSDiscovery/blob/master/CHANGELOG.md#1047---2018-10-12

It's a regular patch release, with no significant change to the UI/application. All standard deployment procedures apply.

@nmacgreg  When you have a moment, please proceed with deployment. Thanks!

**Comment by seanluyk** [comment]
A quick test revealed the following regarding 1.046/7:

- **Send correction link** brings up the submission form, but no email is being delivered (to OTRS) as far as I can tell
- **Rollbar** - how do we know if this is working/is it activated in test?
- **Text me this item/email me this item** - I get a network error if I try to do either of these things and there's a style problem (fields extend past pop up window)

**Comment by seanluyk** [comment]
P.S. the style error applies to all popups from records as well (Librarian View, cite this item)

**Comment by pgwillia** [comment]
replying to https://github.com/ualbertalib/NEOSDiscovery/issues/192#issuecomment-430005365

This is a limitation to how a few of these things have been configured.  As far as I know NEOSDiscovery uses the "test" RAILS_ENV so the mailer and rollbar are not configured in this environment.

The style issue was not fixed in this release.  Please create a new issue.

**Comment by seanluyk** [comment]
@pgwillia the style issue seems to have been introduced in this release - I'll create a new issue

**Comment by seanluyk** [comment]
@pgwillia that's good to know re: the mailer/rollbar not configured in test

**Comment by pgwillia** [comment]
Found #195 in this release.  This release will not be put into production.
