### ISSUE TITLE
Add custom error pages

### ISSUE THREAD

**Issue by pgwillia** [ualbertalib/NEOSDiscovery#200]
Right now it shows the default
![image](https://user-images.githubusercontent.com/1220762/47177762-95088d00-d2d6-11e8-9094-04b94a64e46e.png)

We probably want something like [discovery](https://github.com/ualbertalib/discovery/tree/master/app/views/errors)[.](https://github.com/ualbertalib/discovery/blob/29ad6912d0a89dfde4b1fea5d030ca192d45bcf1/config/routes.rb#L30-L32)
![screenshot from 2018-10-18 13-10-33](https://user-images.githubusercontent.com/1220762/47178015-37287500-d2d7-11e8-9705-4e87910f5a1f.png)
Or better like [jupiter](https://github.com/ualbertalib/jupiter/pull/495/files)

**Comment by weiweishi** [comment]
preferably jupiter's approach: make static public error pages and let rails handle the error pages.
