### ISSUE TITLE
Reminder to Renew/Return Notice - Update/move from iLink

### ISSUE THREAD

**Issue by Andeebee** [ualbertalib/NEOSDiscovery#207]
The reminder notice links to My Account in iLink:

> If you wish to renew, you may do so using My Account at http://catalogue.library.ualberta.ca/myaccount/"

We will need to update this to link to the web services version.

**Comment by seanluyk** [comment]
@Andeebee  - is this about the email notification you receive from iLink or is this something in NEOS Discovery?

**Comment by Andeebee** [comment]
Yes, it's just the email notification. Just didn't want to forget that we'll need to update this at some point.

**Comment by seanluyk** [comment]
@Andeebee thanks, I'll report this to the ILS team

**Comment by seanluyk** [comment]
@Andeebee on second thought...if we link to https://myaccount.library.ualberta.ca/barcode/?neos=true, there are no options for non-barcode logins like there are on this page https://catalogue.library.ualberta.ca/myaccount/

Let me think about this one

**Comment by seanluyk** [comment]
Closing issue for now as it isn't Blacklight specific. Jeremy will work on mocking up a web services version of the my account login page. Once that's done I'll request that the message gets changed.
