### ISSUE TITLE
Remove beta labeling 

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/NEOSDiscovery#216]
Remove beta labelling (in 3 places). @weiweishi @pgwillia @murny I just got a request to expedite this, so if this can make it in the next release that would be great!

I believe that beta labelling exists in three places:

1. Catalogue Landing Page
![screen shot 2018-12-14 at 10 15 45](https://user-images.githubusercontent.com/14880206/50017476-61ba4580-ff89-11e8-83be-5b5ddc62710c.png)
 - Remove the word beta

2. Library Landing Pages 
![screen shot 2018-12-14 at 10 15 56](https://user-images.githubusercontent.com/14880206/50017480-667ef980-ff89-11e8-9c11-d84253aed741.png)
 - Remove the word beta

3. Library Landing Pages (Description)
![screen shot 2018-12-14 at 10 16 08](https://user-images.githubusercontent.com/14880206/50017505-7b5b8d00-ff89-11e8-952c-1bc734856f9b.png)
 - Remove the sentence "This is a beta version of the NEOS Catalogue"

**Comment by seanluyk** [comment]
Perfect, thanks @murny!

**Comment by murny** [comment]
This is now done in PR #223 (description includes screenshots of the change)

**Comment by murny** [comment]
This is now merged into master and will make it out in next release of NEOSDiscovery
