### ISSUE TITLE
[NEOS Discovery] Update Northern Lakes College Library URL

### ISSUE THREAD

**Issue by seanluyk** [ualbertalib/NEOSDiscovery#263]
NLC Library has a new website: https://www.nlclibrary.ca/, which will need to be updated in [libraries.yml](https://github.com/ualbertalib/NEOSDiscovery/blob/f3dc1d6d5a8663481ec480e30b7a6cf5ea6f8c61/config/libraries.yml)

**Comment by weiweishi** [comment]
Completed.
