### ISSUE TITLE
Place hold

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#27]
- [x] Add "holdable" place hold logic
- [x] Style place hold button
- [x] Get Jeremy to build a web services version and link to that

**Comment by redlibrarian** [comment]
@nnunn This logic is in place now, but it's not seeing the "btn hold" css class - I don't know if we want new styling or just reuse the UAL styling for the hold button.

**Comment by nnunn** [comment]
This is styled now.
