### ISSUE TITLE
[NEOSDiscovery]Reserve desk

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#40]
Web services version

**Comment by redlibrarian** [comment]
I've talked to our web developer about building this. It's doable.

**Comment by redlibrarian** [comment]
I'll ask Jeremy to build it. Because it's not connected to record information (in iLink it's just a static link to its own interface), when Jeremy builds this, we'll just have to add a link to it wherever we need to.

**Comment by seanluyk** [comment]
@Andeebee status update - checked in with Jeremy on this, will update this ticket with news

**Comment by seanluyk** [comment]
@Andeebee - Jeremy has completed this work in test: https://web.library.ualberta.ca/reserveroom/reserveexamples/reserves.php

Please let me know if you have any changes to suggest and we'll see if they can be done. This is more or less done in my opinion. Once you give the thumbs up we'll change the current link in the interface

**Comment by theLinkResolver** [comment]
May I suggest changing the word "Search" to "Begins with" or the like. If you search for the word "movements" you do not find the course called "Social Movements" for example.

**Comment by seanluyk** [comment]
Great suggestion, @theLinkResolver  - I've asked Jeremy to change this labeling.

**Comment by seanluyk** [comment]
@theLinkResolver the search is working as expected - there isn't much we can do to change how results are returned when using Symphony web services, unfortunately

**Comment by theLinkResolver** [comment]
@seanluyk Oh I gotcha. I expected a list of course IDs when I searched for course ID but I see this is how it is in the existing service too.

I noted in the existing service we call it Course Number instead of Course ID (which what they are called in Workflows). Is that discrepancy okay? (UA Calendar calls them Course Numbers - I appreciate this is for all of NEOS)

**Comment by seanluyk** [comment]
@theLinkResolver  - thanks, the plan is to send this around more widely once the NEOS group has had a chance to review, and we can incorporate UI changes pretty quickly

**Comment by theLinkResolver** [comment]
@seanluyk sounds good, always good to avoid system jargon. just wanted to confirm if it was intentional to move away from the existing language
