### ISSUE TITLE
"booking module is confusing for clients as hold not allowed - not obvious to go to booking above"

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#54]

**Comment by redlibrarian** [comment]
Use web services to check whether something is Bookable OR Holdable and present the appropriate button. Nothing should be Bookable and Holdable at the same time.

**Comment by redlibrarian** [comment]
We're unsure as to whether Bookable and Holdable are always mutually exclusive, so we'll need a way to unambiguously/intuitively display both "Place Hold" and "Book Item". @nnunn Can we talk about doing a mockup for this?

**Comment by redlibrarian** [comment]
OK, I've added the logic to display a "Book Item" button when the item is bookable. Right now both the Place Hold and the Book Item links just go back to iLink for a hold/booking. When we've deployed the new MyAccount, we will be pointing Place Hold to the Web Services hold service. I need to talk to Jeremy about whether that will work for booking.

**Comment by redlibrarian** [comment]
Example record: http://www.library.ualberta.ca/permalink/opac/7299348/WCH_RAH

**Comment by redlibrarian** [comment]
The link was turned off during (we think) a Symphony upgrade about a year ago. The Workflows end of booking is still working, but it raises the question of whether we need the booking module linked in Blacklight. I've asked @Andeebee and @paulpype-goa to think about this.

**Comment by Andeebee** [comment]
AHS would like to go back to using the booking module with clients - saves staff time, keeps that collection accessible.

**Comment by redlibrarian** [comment]
Our Symphony team is going to look into turning the iLink part of the booking module back on. Until then, I can't see what the booking module looks like or what it points too in order to recreate it in Blacklight. Realistically, this one isn't going to get done before I leave...

**Comment by nnunn** [comment]
I'm not totally sure how to handle this. I don't know where "book item" is supposed to link to.

**Comment by seanluyk** [comment]
@nnunn  - I'll check with Elaine on the status of the booking module.

**Comment by seanluyk** [comment]
No longer a requirement given that booking module is not in use on the iLink side. Closing.
