### ISSUE TITLE
Incorrectly displaying libraries in facets list

### ISSUE THREAD

**Issue by paulpype-goa** [ualbertalib/NEOSDiscovery#79]
The names of a couple of AHS libraries are not displaying properly in the facets list.

![libraries](https://user-images.githubusercontent.com/33127724/32573608-c9726f52-c48b-11e7-803f-3dc0f16b735e.png)

**Comment by redlibrarian** [comment]
This should be fixed now; please check.

**Comment by paulpype-goa** [comment]
It looks good now.
