### ISSUE TITLE
Refworks and Endnote problems.

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#80]

**Comment by Andeebee** [comment]
Export to Refworks -- Opens up in Refworks, but consistently get message that import failed (below)
"Import failed
Oops, we encountered some technical issues. Please try again later."
Export to Endnote -- Successful.

**Comment by redlibrarian** [comment]
Hm. I'm not getting an error message, just a blank import modal window. I'll investigate.

**Comment by redlibrarian** [comment]
It occurs to me that this may be due to the test server being behind a firewall.

**Comment by Andeebee** [comment]
Confirmed successful export to new Refworks.

**Comment by redlibrarian** [comment]
Great. Closing this for now - if the problem reappears we can reopen it, but I think this is fixed.
