### ISSUE TITLE
Book Covers

### ISSUE THREAD

**Issue by Andeebee** [ualbertalib/NEOSDiscovery#83]
I'm seeing instances whereby there is a book cover available for a title in the results list, but when I click into the item the image is not available.

Result List -- https://barking.library.ualberta.ca/?q=Beer+%26+cheese&search_field=all_fields
First Result -- https://barking.library.ualberta.ca/catalog/5917828
Third Result -- https://barking.library.ualberta.ca/catalog/6343146

**Comment by nnunn** [comment]
This is fixed
