### ISSUE TITLE
evideo links urls incorrect for NorQuest McIntyre Media collection

### ISSUE THREAD

**Issue by kzarft** [ualbertalib/NEOSDiscovery#85]
Internet Access urls for our McIntyre Media online videos are pointing to  https://barking.library.ualberta.ca/catalog/ instead of the urls that are in the 856 field of the record. I am not sure if this is something wrong with our record (we noticed that they had the ezproxy prefix hard coded in the 856 and we are fixing the records) or an error in Blacklight.
Two example records are:
https://barking.library.ualberta.ca/catalog/7564475
https://barking.library.ualberta.ca/catalog/7529677

**Comment by redlibrarian** [comment]
This is related to #82 - I'm working on it.

**Comment by redlibrarian** [comment]
Weird. I thought I had fixed this (with #82), but it's still not working...

**Comment by redlibrarian** [comment]
Turns out the latest code release hadn't been deployed. Will check again once deployed to barking.

**Comment by redlibrarian** [comment]
@kzarft This should be working now. Can you take a look at https://fowey.library.ualberta.ca/catalog/7564475 ? Let me know if you can't get to that server.

**Comment by kzarft** [comment]
I don't seem to be able to get to the server.

**Comment by redlibrarian** [comment]
@kzarft Right, sorry - that one's just internal. It should be working on https://barking.library.ualberta.ca/catalog/7564475

**Comment by redlibrarian** [comment]
@kzarft We have the same bug in UAL Discovery. I'm going to have to dig into how to fix it in both applications.

**Comment by redlibrarian** [comment]
The issue with the mismatch between proxy and link should be fixed in issue #104 . The issue of the multiple 856 links is a problem with the Solr indexing, and that may not be so easily fixable...

**Comment by redlibrarian** [comment]
This is a larger issue being worked on as part of UAL Discovery (https://github.com/ualbertalib/discovery/issues/1067). I'm going to close this issue, as this will be resolved as part of the UAL Discovery summer project.
