### ISSUE TITLE
How are Lost or Missing items (shadowed) dealt with in Blacklight?

### ISSUE THREAD

**Issue by kzarft** [ualbertalib/NEOSDiscovery#87]
When I searches for "Book Thief" or "5 Love Languages" and filter for NorQuest the following two records are in the results list but are actually lost:
https://barking.library.ualberta.ca/catalog/5472675
https://barking.library.ualberta.ca/catalog/4135094

How are Lost or Missing items dealt with in Blacklight?

**Comment by redlibrarian** [comment]
In theory, any shadowed *item* (including lost and missing) simply won't show in the holdings table on the record; any shadowed *bib record* (i.e. if there are no visible items attached) should get removed from the index completely. In practice, this doesn't work very smoothly and we rely on a monthly full reindex to handle any shadowed records. I'm working on fixing that.

**Comment by redlibrarian** [comment]
What's happening in this case, I think, is that there are no visible NorQuest *items*, so nothing appears in the holdings table, but there are other items attached to the record, so the bib record itself is still present/findable. The bib record hasn't been updated to remove NorQuest as an owning library, and in fact, I'm not to clear on how that works in practice. It should appear as an update bib record...

**Comment by redlibrarian** [comment]
This problem still exists, but I'm not sure why, as we've been through several full reindexes since then...

**Comment by redlibrarian** [comment]
Ah, interesting. The institution code is taken from marc 596. In the catalogue record (in Symphony), marc 596a still lists Norquest (library code 3) as a library that owns these items. So this is a cataloguing issues rather than a Blacklight problem.

**Comment by redlibrarian** [comment]
@kzarft We should discuss the best way to fix this. As I say, I think this is down to how the items have been catalogued.

**Comment by kzarft** [comment]
My cataloguer is telling me that we don't have a way to edit the 596 field in the catalog record.  I think this will be happening for lost and missing items for all NEOS libraries as it will show the library holds the item in the Results list, but in the detail record there will be no holding as it is shadowed in Symphony.  I can see that MacEwan also has a lost copy of 5 Love Languages on the same record that is showing in the same way.  This might need a broader conversation with the group because if we move away from iLink, is shadowing the Lost items still going to be useful.  I also see the same type of results in both EDS and WorldCat Discovery.

**Comment by redlibrarian** [comment]
@kzarft What do you think should be done with this issue? It seems like it requires a larger conversation with tech services...?

**Comment by kzarft** [comment]
@redlibrarian Yes, I think this would be a larger conversation with tech services.

**Comment by seanluyk** [comment]
This is also being address for UAL Blacklight

**Comment by seanluyk** [comment]
Resolved in UAL discovery/NEOS discovery
