### ISSUE TITLE
Report a Problem link

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#96]
Move from UAL Discovery into NEOS Discovery. Make sure it includes the record URL.

**Comment by redlibrarian** [comment]
OK, this has been added. We'll need to test when it's in production.

**Comment by Andeebee** [comment]
Update help referral link (currently UofA) for public release. 

Who receives the Send a Correction submissions?

**Comment by redlibrarian** [comment]
I think this goes to our bibhelp team - the same as with the classic NEOS catalogue?

**Comment by redlibrarian** [comment]
OK, this is working now. The link at the bottom of the form goes to whichever library is currently being used.
