### ISSUE TITLE
SMS This link is populated with American carriers

### ISSUE THREAD

**Issue by paulpype-goa** [ualbertalib/NEOSDiscovery#97]
If we are going to provide this service, we need to make sure it works with Canadian carriers. Otherwise, we need to hide the link.

**Comment by redlibrarian** [comment]
Hi Paul,

We have this working with Canadian carriers for I UAL, but I forgot to
update the list here
 Thanks for catching that.

**Comment by paulpype-goa** [comment]
Great! Also, when I try to email a record, I get "Incomplete response received from application".

**Comment by redlibrarian** [comment]
The carriers list is updated. I'm going to create a new issue for the email problem.
