### ISSUE TITLE
Deploy My Account and link to new Place Hold URL

### ISSUE THREAD

**Issue by redlibrarian** [ualbertalib/NEOSDiscovery#98]

**Comment by redlibrarian** [comment]
This is done; just waiting to push it into production.

**Comment by Andeebee** [comment]
Action after the hold is placed is to return to item record - it brings users to UofA Blacklight record.

**Comment by redlibrarian** [comment]
@Andeebee Weird - when I use the Place Hold, it opens in a new window, with a message to close the window to return to the record you were looking at. Are you seeing something else? If you don't see that message, or see a different message, can you take a screenshot an add it to this issue? Thanks.

**Comment by redlibrarian** [comment]
@Andeebee Ah, I see the problem now. I'll have our developer fix that.

**Comment by Andeebee** [comment]
After the hold is placed you get a screen with green confirmation text, and link that says Go back to item.

**Comment by Andeebee** [comment]
https://myaccount.library.ualberta.ca/barcode/placeholdsuccess

**Comment by redlibrarian** [comment]
I've asked our developer to fix it; it will be a quick fix and won't require a code deploy.

**Comment by redlibrarian** [comment]
@Andeebee This should be fixed now - can you confirm? Thanks!

**Comment by Andeebee** [comment]
Confirmed.
